CREATE TABLE enzymecode (code_id TEXT, desc TEXT);
CREATE TABLE sfld_map (cluster_id TEXT, sfld_id TEXT);
CREATE TABLE sfld_desc (sfld_id TEXT, sfld_desc TEXT, sfld_color TEXT);
CREATE TABLE swissprot (cluster_id TEXT, uniprot_id TEXT, function TEXT);
CREATE INDEX swissprot_cluster_id_idx ON swissprot (cluster_id);
CREATE TABLE kegg (cluster_id TEXT, uniprot_id TEXT, kegg TEXT);
CREATE INDEX kegg_cluster_id_idx ON kegg (cluster_id);
CREATE TABLE pdb (cluster_id TEXT, uniprot_id TEXT, pdb TEXT);
CREATE TABLE taxonomy (cluster_id TEXT, uniprot_id TEXT, domain TEXT, kingdom TEXT, phylum TEXT, class TEXT, taxorder TEXT, family TEXT, genus TEXT, species TEXT);
CREATE INDEX taxonomy_cluster_id_idx ON taxonomy (cluster_id);
CREATE INDEX taxonomy_domain_idx ON taxonomy (domain);
CREATE INDEX taxonomy_kingdom_idx ON taxonomy (kingdom);
CREATE INDEX taxonomy_phylum_idx ON taxonomy (phylum);
CREATE INDEX taxonomy_class_idx ON taxonomy (class);
CREATE INDEX taxonomy_taxorder_idx ON taxonomy (taxorder);
CREATE INDEX taxonomy_family_idx ON taxonomy (family);
CREATE INDEX taxonomy_genus_idx ON taxonomy (genus);
CREATE INDEX taxonomy_species_idx ON taxonomy (species);
CREATE TABLE id_mapping (cluster_id TEXT, uniprot_id TEXT);
CREATE INDEX id_mapping_uniprot_id_idx ON id_mapping (uniprot_id);
CREATE INDEX id_mapping_cluster_id_idx ON id_mapping (cluster_id);
CREATE TABLE id_mapping_uniref50 (cluster_id TEXT, uniref50_id TEXT);
CREATE INDEX id_mapping_uniref50_id_idx ON id_mapping_uniref50 (uniref50_id);
CREATE INDEX id_mapping_uniref50_cluster_id_idx ON id_mapping_uniref50 (cluster_id);
CREATE TABLE id_mapping_uniref90 (cluster_id TEXT, uniref90_id TEXT);
CREATE INDEX id_mapping_uniref90_id_idx ON id_mapping_uniref90 (uniref90_id);
CREATE INDEX id_mapping_uniref90_cluster_id_idx ON id_mapping_uniref90 (cluster_id);
CREATE TABLE network (cluster_id TEXT, title TEXT, name TEXT, desc TEXT);
CREATE INDEX network_cluster_id_idx ON network (cluster_id);
CREATE TABLE region (cluster_id TEXT, region_id TEXT, region_index INT, name TEXT, number TEXT, coords TEXT);
CREATE TABLE families (cluster_id TEXT, family TEXT, family_type TEXT);
CREATE INDEX families_cluster_id_idx ON families (cluster_id);
CREATE TABLE family_info (family TEXT PRIMARY KEY, description TEXT);
CREATE INDEX family_info_name_idx ON family_info (family);
CREATE TABLE size (cluster_id TEXT, uniprot INT DEFAULT 0, uniref90 INT DEFAULT 0, uniref50 INT DEFAULT 0);

